function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 24-Feb-2020 11:57:46

persistent Hd;

if isempty(Hd)
    
    Fpass1 = 55;    % First Passband Frequency
    Fstop1 = 59;    % First Stopband Frequency
    Fstop2 = 61;    % Second Stopband Frequency
    Fpass2 = 65;    % Second Passband Frequency
    Apass1 = 1;     % First Passband Ripple (dB)
    Astop  = 60;    % Stopband Attenuation (dB)
    Apass2 = 1;     % Second Passband Ripple (dB)
    Fs     = 200;  % Sampling Frequency
    
    h = fdesign.bandstop('fp1,fst1,fst2,fp2,ap1,ast,ap2', Fpass1, Fstop1, ...
        Fstop2, Fpass2, Apass1, Astop, Apass2, Fs);
    
    Hd = design(h, 'equiripple');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

