function y = Filtro_Pasa_altas(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 17-Feb-2020 01:27:54

persistent Hd;

if isempty(Hd)
    
    Fstop = 5;    % Stopband Frequency
    Fpass = 5.1;  % Passband Frequency
    Astop = 20;   % Stopband Attenuation (dB)
    Apass = 1;    % Passband Ripple (dB)
    Fs    = 11;   % Sampling Frequency
    
    h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

