function Hd = FRB
%GETFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
% Generated on: 24-Feb-2020 00:29:51

Fpass1 = 55;   % First Passband Frequency
Fstop1 = 59;   % First Stopband Frequency
Fstop2 = 61;   % Second Stopband Frequency
Fpass2 = 65;   % Second Passband Frequency
Apass1 = 1;    % First Passband Ripple (dB)
Astop  = 60;   % Stopband Attenuation (dB)
Apass2 = 1;    % Second Passband Ripple (dB)
Fs     = 150;  % Sampling Frequency

h = fdesign.bandstop('fp1,fst1,fst2,fp2,ap1,ast,ap2', Fpass1, Fstop1, ...
    Fstop2, Fpass2, Apass1, Astop, Apass2, Fs);

Hd = design(h, 'equiripple');


